/**
 * GitHub PR creation via Octokit.
 */

import { Octokit } from '@octokit/rest';
import { logger } from '@mrck-labs/ralphy-shared';

export interface CreatePROptions {
  owner: string;
  repo: string;
  title: string;
  body: string;
  head: string;
  base: string;
}

export interface PRResult {
  url: string;
  number: number;
}

export function createOctokitClient(token: string): Octokit {
  return new Octokit({ auth: token });
}

export async function createPullRequest(
  octokit: Octokit,
  options: CreatePROptions
): Promise<PRResult> {
  const { owner, repo, title, body, head, base } = options;

  logger.info(`Creating PR: ${title}`);
  logger.info(`  ${head} -> ${base}`);

  const response = await octokit.pulls.create({
    owner,
    repo,
    title,
    body,
    head,
    base,
  });

  logger.success(`PR created: ${response.data.html_url}`);

  return {
    url: response.data.html_url,
    number: response.data.number,
  };
}

export function formatPRBody(issueKey: string, summary: string): string {
  return `## Summary

Automated changes for [${issueKey}](https://yourcompany.atlassian.net/browse/${issueKey})

${summary}

---

Generated by [Ralphy Webhook Service](https://github.com/yourorg/ralphy)
`;
}
